name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-content:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown-link-check
        pip install yamllint
    
    - name: Validate Markdown Links
      run: |
        find . -name "*.md" -exec markdown-link-check {} \;
    
    - name: Check for TODO items
      run: |
        echo "Checking for TODO items..."
        grep -r "TODO\|FIXME\|XXX" --include="*.md" . || true
    
    - name: Validate file structure
      run: |
        python scripts/utilities/validate-structure.py

  spell-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Spell Check
      uses: streetsidesoftware/cspell-action@v2
      with:
        files: "**/*.md"
        config: ".cspell.json"

  aws-cli-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Validate AWS CLI commands
      run: |
        # Test basic AWS CLI functionality
        aws sts get-caller-identity
        echo "AWS CLI validation complete"
